# device: mps
device: cpu

model:
  name: PortfolioNet
  input_dim: 8
  output_dim: 4
  hidden_dim: 64

loss_fn:
  name: SharpeRatioLoss

optimizer:
  name: Adam
  lr: 1.e-3

train_loader:
  name: PortfolioDataLoader
  root: data/yfinance
  batch_size: 64
  num_workers: 4
  shuffle: true

trainer:
  name: PortfolioTrainer
  num_epochs: 100
