# device: mps
device: cpu

num_epochs: 100

model:
  name: PortfolioNet
  input_dim: 8
  output_dim: 4
  hidden_dim: 64

loss_fn:
  name: SharpeRatioLoss

optimizer:
  name: RAdam
  lr: 1.e-3
  weight_decay: 1.e-5

scheduler:
  name: CosineAnnealingLR
  T_max: $num_epochs
  eta_min: 1.e-6

train_loader:
  name: PortfolioDataLoader
  dataset_params:
    root: data/yfinance
    window: 50
    since: "2008-01-01"
    until: "2020-01-01"
  batch_size: 64
  num_workers: 1
  shuffle: true

valid_loader:
  name: PortfolioDataLoader
  dataset_params:
    root: data/yfinance
    window: 50
    since: "2020-01-01"
    until: "2022-01-01"
  batch_size: 64
  num_workers: 1
  shuffle: true

trainer:
  name: PortfolioTrainer
  num_epochs: $num_epochs
